openapi: 3.0.3
info:
  title: UK Internal Market EORI Authorisaton Checker Reference Guide
  description: |
    This API allows Fast Parcel Operators (FPOs) and 3rd party users to check if the holders of provided EORI Numbers have a valid UKIM authorisation.
    The aim is to avoid possible rejections of goods moving through from GB-NI, which could physically stop the B2B parcels.
    The API is based on REST principles with a single POST method endpoint that returns data in JSON format. It uses standard HTTP error response codes. 
    Use the API to request the UKIM Authorization Status of between 1 to 3000 EORIs passed as an array. 

    Note: The API endpoint relates only to Great Britain and Northern Ireland.
  contact: {}
  version: 0.0.1
servers:
  - url: 'https://test-api.service.hmrc.gov.uk'
    description: |
      URL for the Test Environment
  - url: 'https://api.service.hmrc.gov.uk'
    description: |
      URL for the Live Environment
tags:
  - name: Authorisations
    description: |
paths:
  /customs/uk-internal-market/authorisations:
    post:
      tags:
        - Endpoint for Authorisations
      summary: |
        Request Authorisation Status for user provided EORIs
      description: |
        Use this method to request the UKIM Authorization Status of between 1 and 3000 EORIs. EORIs are taken as a Comma Separated List (CSV) and stored as a string type array . 
        
        There are two string body parameters - eoris and date.  
        

        
      operationId: requestAuth
      requestBody:
        description: | 
          The payload of the API request. 
          
          Request Example:
          
          curl -X POST "https://test-api.service.hmrc.gov.uk/customs/uk-internal-market/authorisations"   
  
                  
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: |
            Success - Authorised. A list of EORI Numbers provided with their authorised status as boolean 'true'. 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Authorisations'
        '400':
          description: |
            Validation failure. The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
        '403':
          description: |
            Forbidden. The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
        '405':
          description: |
            Method not allowed. The request method is known by the server but is not supported by the target resource. 
        '406':
          description: |
            Not acceptable. This response is sent when the web server, after performing server-driven content negotiation, doesn't find any content that conforms to the criteria given by the user agent.
        '429':
          description: |
            Request in excess of rate limit. The user has sent too many requests in a given amount of time.
        '500':
          description: |
            Internal Server Error. The server has encountered a situation it does not know how to handle.
      security:
        - applicationRestricted: []
components:
  securitySchemes:
    applicationRestricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating application restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header.
        See https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints for details.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes: { }
  schemas:
    Request:
      type: object
      properties:
        date:
          type: string
          example: 2024-02-31
        eoris:
          type: array
          items:
            type: string
            example: GB123123123123s
    Authorisations:
      type: object
      properties:
        date:
          type: string
          example: 2024-02-31
        eoris:
          type: array
          items:
            type: object
            properties:
              eori:
                type: string
                example: GB123123123123
              authorised:
                type: boolean
                example: true
